name: C++ CI Accelerator Demo

on: [push, pull_request]

jobs:
  baseline:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install deps
        run: sudo apt-get update && sudo apt-get install -y cmake g++
      - name: Build
        run: time ./scripts/build-opencv.sh

  with-ccache:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install deps
        run: sudo apt-get update && sudo apt-get install -y cmake g++ ccache
      - name: Setup ccache
        uses: hendrikmuhs/ccache-action@v1.2
        with:
          key: opencv-demo-v1

      - name: Build with ccache
        run: time ./scripts/build-opencv.sh

  with-docker:
    name: üê≥ With Docker + ccache
    runs-on: ubuntu-latest
    container: ghcr.io/${{ github.repository_owner }}/cpp-ci-accelerator:latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup ccache cache
        uses: hendrikmuhs/ccache-action@v1.2
        with:
          key: opencv-demo-v2

      - name: Build OpenCV
        run: time ./scripts/build-opencv.sh